### PR TITLE
Replay-source demo file

### PR DESCRIPTION
**Pull request by simonpfeifhofer**

### CODE REVIEW

**Review by chlumper — APPROVED** [review]
LGTM!

**Comment by mayrmax** [comment]
all dtId's should be UUID

**Comment by simonpfeifhofer** [comment]
> all dtId's should be UUID

Why? In order to avoid collisions later on?

**Comment by simonpfeifhofer** [comment]
> > all dtId's should be UUID
> 
> Why? In order to avoid collisions later on?

We accept dtid's which are NOT valid UUIDs at the current stage.

**Pull request merged**
